source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'rails-api'
gem 'active_model_serializers'


group :development do
  gem 'sqlite3'
end

group :test do
  gem 'rspec-rails'
end

group :production do
  gem 'pg'
end
